/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_video_trimmer_natives_VideoTrimmer */

#ifndef _Included_net_video_trimmer_natives_VideoTrimmer
#define _Included_net_video_trimmer_natives_VideoTrimmer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_video_trimmer_natives_VideoTrimmer
 * Method:    trim
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_cn_com_wanyueliang_tomato_utils_ffmpeg_VideoTrimmerService_trim
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
