/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_wanyueliang_tomato_utils_ffmpeg_VideoTrimmer_FinishListener */

#ifndef _Included_cn_com_wanyueliang_tomato_utils_ffmpeg_VideoTrimmer_FinishListener
#define _Included_cn_com_wanyueliang_tomato_utils_ffmpeg_VideoTrimmer_FinishListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
